version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stashable
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - api-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  cache:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  postgres_data:
